[project]
name = "bitbirch"
version = "0.1.0"
requires-python = "~= 3.10.0"

# install all sub-modules including namespace packages
[tool.setuptools.packages]
find = {}

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"
